<?php

namespace App\Http\Requests\Admin\User;

use Illuminate\Foundation\Http\FormRequest;

class CreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name'                   => 'required|max:50|min:2',
            'email'                  => 'required|unique:users|email',
            'password'               => 'required|max:30|min:6',
            'password_confirmation'  => 'required_with:password|same:password|min:6',
        ];
    }

    public function messages()
    {
        parent::messages(); // TODO: Change the autogenerated stub

        return [
            'name.required'               => 'Name không được để trống',
            'name.max'                    => 'Name vượt quá 50 ký tự',
            'email.required'              => 'Email không được để trống',
            'email.unique'                => 'Email đã tồn tại',
            'password.required'           => 'PassWord không được để trống',
            'password.max'                => 'PassWord quá dài',
            'password.min'                => 'PassWord quá ngắn',
        ];
    }

    protected function failedValidation(\Illuminate\Contracts\Validation\Validator $validator)
    {
        // Lưu thông báo lỗi vào session
        $this->session()->flash('errors', $validator->errors());

        parent::failedValidation($validator);
    }
}
